<div class="entry">
    вошли как <?= $this->user['name']; ?>
    <form action="/user/logout">
        <input type="submit" value="Выйти">
    </form>
</div>


<br>
<br>
<div class="form">
    <form enctype="multipart/form-data" action="/blog/sendPost" method="post">
        Message:<br>
        <textarea name="message" style="width: 250px; height: 100px;"></textarea><br>
        Прикрепить картинку:<br>
        <input name="userfile" type="file"/><br>
        <input type="submit" value="Send">
    </form>
</div>


<?php foreach ($this->messages as $message): ?>
    <div class="post">
        <span class="user"><?php echo "Пользователь <b>" . $message['user_name'] . "</b> Отправил сообщение в: " . $message['created_at']; ?></span>
        <div class="message"><?= $message['text']; ?></div>
        <?php if(in_array($_SESSION['id'], $this->AdminList)):?>
        <form action="/blog/deletePost" method="post">
            <input type="hidden" name="post_id" value="<?= $message['id'] ?>"><br>
            <input type="submit" value="Удалить">
        </form>
        <?php endif;?>
        <?php if ($message['image']): ?>
        <img src="/blog/image/?filePath=<?=$message['image'];?>">
        <?php echo "<br>"; endif;?>
    </div>
<?php endforeach; ?>


<style>
    .entry {
        position: absolute;
        top: 0;
        right: 0;
    }

    .form {
        width: 250px;
        margin: auto;
    }

    .post {
        border: 1px solid grey;
        margin-top: 10px;
        padding: 5px;
        width: 250px;
        margin: auto;
    }

    .user {
        color: grey;
        font-size: 11px;
    }

    .message {
        margin-top: 5px;
        padding-left: 5px;
    }
</style>